### ISSUE TITLE
Error on running npm start

### ISSUE THREAD

**Issue by Gabri** [clementpl/influx-crypto-watcher#2]
Hello,
I'd like to try your project.
I've followed instructions (npm install & npm run docker-start [they were ok]).
Then running 'npm start' I get (it seems a dependecy problem):

[...]
Creating grafana  ... done
Creating mongodb  ... done
Creating influxdb ... done
$ npm start

> influx-crypto-watcher@1.0.0 start /mnt/workspace/ws/git/cry/influx-crypto-watcher
> ts-node -P ./tsconfig.json src/index.ts

2019-04-24T14:09:12+02:00 [info]: [MONGODB] Connection successful: mongodb://localhost:27017/dev-crypto-watcher
2019-04-24T14:09:12+02:00 [info]: [INFLUXDB] Connection successful: localhost:8086
2019-04-24T14:09:12+02:00 [error]: Cannot find module '@hapi/joi'
Error: Cannot find module '@hapi/joi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/mnt/workspace/ws/git/cry/influx-crypto-watcher/node_modules/lout/lib/index.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.<anonymous> (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:47:67)
    at Generator.next (<anonymous>)
    at /mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:7:71
    at new Promise (<anonymous>)

2019-04-24T14:09:12+02:00 [error]: [API] Cannot start api
Error: [API] Cannot start api
    at Function.<anonymous> (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:65:13)
    at Generator.next (<anonymous>)
    at /mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:3:12)
    at Function.create (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:35:16)
    at Object.<anonymous> (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/server.ts:43:30)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/server.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

2019-04-24T14:09:12+02:00 [error]: [API] Cannot start api
Error: [API] Cannot start api
    at Function.<anonymous> (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:65:13)
    at Generator.next (<anonymous>)
    at /mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:3:12)
    at Function.create (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/api/API.ts:35:16)
    at Object.<anonymous> (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/server.ts:43:30)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/server.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

2019-04-24T14:09:12+02:00 [error]: Unexpected Error
Error: Unexpected Error
    at server_1.startServer.catch.error (/mnt/workspace/ws/git/cry/influx-crypto-watcher/src/index.ts:9:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! influx-crypto-watcher@1.0.0 start: `ts-node -P ./tsconfig.json src/index.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the influx-crypto-watcher@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gabri/.npm/_logs/2019-04-24T12_09_13_059Z-debug.log

Thanks

**Comment by clementpl** [comment]
Hello,

Yes it looks like a dependency problem, its weird because I use travis-ci and the build is passing.
You didn't get any error during your npm install ?
Anyway try to install joi (https://github.com/hapijs/joi)

npm install --save @hapi/joi

If it doesn't work you it should be because of a new version upgrade.
In package.json
replace:
   "joi": "^14.3.0",
with:
   "joi": "14.3.0",

The "^" is getting newest version if available (my last build on travis was 2 month ago so maybe)
I should add a package-lock.json to avoid version problems.

hope this helps

**Comment by Gabri** [comment]
I had other problems, but using latest version of hapi it passed (^18.1.0).
I needed to create manually this folder node_modules/lout/**templates/helpers**
Now it seems to work (I pass to the other project)
Thanks

**Comment by clementpl** [comment]
Ok cool !
Let me know if you got any problem or if you need more information about the influx-crypto-trader project.
Everything is not well documented yet, still under developpement (but slowly I'm working actually, no time available...).
